# Generated by Django 5.2.5 on 2025-08-12 14:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ORBIS Financial', max_length=200)),
                ('symbol', models.CharField(default='ORBIS', max_length=10)),
                ('sector', models.CharField(default='Financial Services', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('founded_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PredictionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_date', models.DateField()),
                ('target_date', models.DateField()),
                ('predicted_revenue', models.DecimalField(decimal_places=2, max_digits=15)),
                ('predicted_profit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('predicted_profit_margin', models.DecimalField(decimal_places=4, max_digits=8)),
                ('confidence_score', models.DecimalField(decimal_places=4, max_digits=5)),
                ('model_used', models.CharField(default='LSTM', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='core.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ceo', 'CEO'), ('analyst', 'Business Analyst'), ('manager', 'Manager'), ('employee', 'Employee')], max_length=20)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('dashboard_preferences', models.JSONField(default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyFinancialData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('day_of_week', models.CharField(max_length=10)),
                ('month', models.CharField(max_length=10)),
                ('year', models.IntegerField(db_index=True)),
                ('quarter', models.CharField(db_index=True, max_length=2)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=15)),
                ('sales', models.DecimalField(decimal_places=2, max_digits=15)),
                ('expenditure', models.DecimalField(decimal_places=2, max_digits=15)),
                ('profit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('profit_margin', models.DecimalField(decimal_places=4, max_digits=8)),
                ('cumulative_revenue', models.DecimalField(decimal_places=2, max_digits=20)),
                ('cumulative_profit', models.DecimalField(decimal_places=2, max_digits=20)),
                ('revenue_growth_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('profit_growth_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('rolling_avg_revenue_7d', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('rolling_avg_revenue_30d', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_data', to='core.company')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date', 'company'], name='core_dailyf_date_712851_idx'), models.Index(fields=['year', 'quarter'], name='core_dailyf_year_e267f7_idx'), models.Index(fields=['profit_margin'], name='core_dailyf_profit__3e28ea_idx')],
                'unique_together': {('company', 'date')},
            },
        ),
        migrations.CreateModel(
            name='QuarterlySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('quarter', models.CharField(max_length=2)),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_sales', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_expenditure', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_profit', models.DecimalField(decimal_places=2, max_digits=20)),
                ('avg_profit_margin', models.DecimalField(decimal_places=4, max_digits=8)),
                ('best_day_revenue', models.DecimalField(decimal_places=2, max_digits=15)),
                ('worst_day_revenue', models.DecimalField(decimal_places=2, max_digits=15)),
                ('days_profitable', models.IntegerField()),
                ('days_in_quarter', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarterly_summaries', to='core.company')),
            ],
            options={
                'ordering': ['-year', '-quarter'],
                'unique_together': {('company', 'year', 'quarter')},
            },
        ),
        migrations.CreateModel(
            name='YearlySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_profit', models.DecimalField(decimal_places=2, max_digits=20)),
                ('avg_daily_revenue', models.DecimalField(decimal_places=2, max_digits=15)),
                ('avg_profit_margin', models.DecimalField(decimal_places=4, max_digits=8)),
                ('growth_rate_revenue', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('growth_rate_profit', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearly_summaries', to='core.company')),
            ],
            options={
                'ordering': ['-year'],
                'unique_together': {('company', 'year')},
            },
        ),
    ]
