# Generated by Django 5.2.5 on 2025-08-13 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ticker_symbol', models.CharField(blank=True, max_length=10, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(default='United States', max_length=100)),
                ('founded_year', models.IntegerField(blank=True, null=True)),
                ('employee_count', models.IntegerField(blank=True, null=True)),
                ('market_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_type', models.CharField(choices=[('CSV', 'CSV Import'), ('EXCEL', 'Excel Import'), ('API', 'API Import'), ('MANUAL', 'Manual Entry')], max_length=50)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('records_imported', models.IntegerField(default=0)),
                ('records_failed', models.IntegerField(default=0)),
                ('import_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('PARTIAL', 'Partially Completed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('REVENUE_DROP', 'Revenue Drop'), ('PROFIT_LOSS', 'Profit Loss'), ('EXPENSE_SPIKE', 'Expense Spike'), ('MARGIN_DECLINE', 'Margin Decline'), ('CASH_FLOW', 'Cash Flow Issue'), ('PERFORMANCE', 'Performance Alert')], max_length=50)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('threshold_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.company')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('CEO', 'Chief Executive Officer'), ('CFO', 'Chief Financial Officer'), ('ANALYST', 'Business Analyst'), ('MANAGER', 'Manager'), ('EMPLOYEE', 'Employee')], default='EMPLOYEE', max_length=50)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('access_level', models.CharField(choices=[('BASIC', 'Basic Access'), ('STANDARD', 'Standard Access'), ('PREMIUM', 'Premium Access'), ('EXECUTIVE', 'Executive Access')], default='BASIC', max_length=20)),
                ('dashboard_preferences', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyFinancialData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('sales', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('expenditure', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('operating_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cost_of_goods_sold', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('gross_profit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('profit_margin', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_assets', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_liabilities', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cash_and_equivalents', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ebitda', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ebit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('free_cash_flow', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('stock_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('volume', models.IntegerField(default=0)),
                ('market_cap', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('customer_count', models.IntegerField(default=0)),
                ('transaction_count', models.IntegerField(default=0)),
                ('average_transaction_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_data', to='core.company')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['company', 'date'], name='core_dailyf_company_8f4d7d_idx'), models.Index(fields=['date'], name='core_dailyf_date_edddb3_idx'), models.Index(fields=['year', 'month'], name='core_dailyf_year_744f73_idx')],
                'unique_together': {('company', 'date')},
            },
        ),
        migrations.CreateModel(
            name='QuarterlySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('quarter', models.IntegerField()),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_profit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('avg_profit_margin', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('revenue_growth', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('profit_growth', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarterly_data', to='core.company')),
            ],
            options={
                'ordering': ['-year', '-quarter'],
                'unique_together': {('company', 'year', 'quarter')},
            },
        ),
    ]
