# Generated by Django 5.2.5 on 2025-09-03 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_onetimepassword'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='onetimepassword',
            new_name='core_onetim_user_id_90d06c_idx',
            old_name='core_onetime_user_0a9c8d_idx',
        ),
        migrations.RenameIndex(
            model_name='onetimepassword',
            new_name='core_onetim_expires_2b42c7_idx',
            old_name='core_onetime_expires_3b7b44_idx',
        ),
    ]
